CREATE SEQUENCE sequence_usuario START WITH 1 INCREMENT BY 50;

CREATE TABLE "user" (
  id BIGINT NOT NULL,
   name VARCHAR(255) NOT NULL,
   email VARCHAR(255) NOT NULL,
   registry_date TIMESTAMP NOT NULL,
   CONSTRAINT pk_user PRIMARY KEY (id)
);