
CREATE SEQUENCE meme_category_sequence START WITH 1 INCREMENT BY 50;

CREATE TABLE MEME_CATEGORY (
   id BIGINT NOT NULL,
   name VARCHAR(255) NOT NULL,
   description VARCHAR(255) NOT NULL,
   registry_date TIMESTAMP NOT NULL,
   CONSTRAINT pk_memecategory PRIMARY KEY (id)
);